config/routes.rb
Rails.application.routes.draw do

  devise_for :users,controllers:{
    sessions: 'users/sessions'
  }

  root to: 'homes#index'

  resources :makes, only: [:create, :destroy]

  resources :ingredients, only: [:create, :destroy]

  resources :recipes do

    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    resources :reports, only: [:create, :destroy]
  end

  resources :homes, only: [:index]

  resources :likes, only: [:create, :destroy]

  get 'users/confirm' => 'users#confirm'
  patch 'users/hide' => 'users#hide'
  put 'users/hide' => 'users#hide'

  get 'users/following'
  get 'users/followers'
  get 'users/recipes'
  get 'users/likes'
  get 'users/reports'

  resources :users, only: [:show, :edit, :update] do
    member do
      get :following, :followers, :recipes, :likes, :reports
    end
  end
  resources :ralationships, only: [:create, :destroy]

  get 'homes/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :recipe
  #バリデーション
  validates :content, presence: true, length: { maximum: 300 }

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @recipe = Recipe.find(params[:recipe_id])
    #投稿に紐づいたコメントを作成
    @comments = @recipe.comments.order(:created_at)
    @comment = @recipe.comments.build(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    render :index
  end

  def destroy
    @comment = Comment.find(params[:id])
    @recipe = @comment.recipe
    @comments = @recipe.comments.order(:created_at)
    @comment.destroy
    render :index
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :recipe_id, :user_id)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<!-- コメント入力フォーム ------------------------------------------------------------>
<%= form_with(model: [recipe, comment], url: recipe_comments_path(recipe) ) do |f| %>
    <%= f.text_area :content, class: "input-mysize" %>
    <%= f.submit "送信", class: "btn btn-outline-dark comment-submit float-right" %>
<% end %>

app/views/comments/_index.html.erb
<% if @comment.errors.any? %>
<ul>
  <% @comment.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>
<!-- コメント内容(２件) ------------------------------------------------------------------>
<%= comments.count %>件コメント
<h6 class="more" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">もっと見る....</h6>
<ul>
  <% comments.limit(2).each do |comment| %>
  <% unless comment.id.nil? %>
  <li class="comment-container">
    <div class="comment-box">
      <div class="row">
        <div class="comment-avatar col-xs-1">
          <%= attachment_image_tag comment.user, :profile_image,:fill, 40,40, fallback: "no_image.jpg", class:"comment-image small_image_size" %>
        </div>
        <p><%= link_to "@#{comment.user.nickname}", user_path(comment.user.id) %></p>
      </div>
      <div class="comment-text">
        <div class="comment-entry">
          <div class="row">
            <%= comment.content %>
          </div>
          <div class="row">
            <% if comment.user == current_user %>
            <%= link_to recipe_comment_path(comment.recipe_id, comment.id), method: :delete, remote: true, class: "comment_destroy" do %>
            <i class="fas fa-trash pull-right" style="color: red;"></i>
            <% end %>
            <% end %>
          </div>
        </div>
        <span class="comment-date pull-right">
          <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
        </span>
      </div>
    </div>
  </li>
  <% end %>
  <% end %>
</ul>
<!-- コメント内容(3件目以降) ------------------------------------------------------------------>
<div class="collapse" id="collapseExample">
  <ul>
    <% comments.offset(2).each do |comment| %>
    <% unless comment.id.nil? %>
    <li class="comment-container">
      <div class="comment-box">
        <div class="row">
          <div class="comment-avatar col-xs-1">
            <%= attachment_image_tag comment.user, :profile_image, :fill, 40,40, fallback: "no_image.jpg", class:"comment-image small_image_size" %>
          </div><p><%= link_to "@#{comment.user.nickname}", user_path(comment.user.id) %></p>
        </div>
        <div class="comment-text">
          <div class="comment-entry">
            <div class="row">
              <%= comment.content %>
            </div>
            <div class="row">
              <% if comment.user == current_user %>
              <%= link_to recipe_comment_path(comment.recipe_id, comment.id), method: :delete, remote: true, class: "comment_destroy" do %>
              <i class="fas fa-trash pull-right" style="color: red;"></i>
              <% end %>
              <% end %>
            </div>
          </div>
          <span class="comment-date pull-right">
            <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
          </span>
        </div>
      </div>
    </li>
    <% end %>
    <% end %>
  </ul>
</div>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comments }) %>")

$("textarea").val('')