config/routes.rb
Rails.application.routes.draw do

  devise_for :users,controllers:{
    sessions: 'users/sessions'
  }

  root to: 'homes#index'

  resources :makes, only: [:create, :destroy]

  resources :ingredients, only: [:create, :destroy]

  resources :recipes do

    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    resources :reports, only: [:create, :destroy]
  end

  resources :homes, only: [:index]

  resources :likes, only: [:create, :destroy]

  get 'users/confirm' => 'users#confirm'
  patch 'users/hide' => 'users#hide'
  put 'users/hide' => 'users#hide'

  get 'users/following'
  get 'users/followers'
  get 'users/recipes'
  get 'users/likes'
  get 'users/reports'

  resources :users, only: [:show, :edit, :update] do
    member do
      get :following, :followers, :recipes, :likes, :reports
    end
  end
  resources :ralationships, only: [:create, :destroy]

  get 'homes/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && (self.is_member_status == false)
  end

  attachment :profile_image

  has_many :likes, dependent: :destroy
  has_many :like_recipes, through: :likes, source: :recipe

  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reports, dependent: :destroy

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship",  dependent: :destroy
  has_many :following, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  validates :profile_text, length: { maximum: 80 }
  validates :nickname, presence: true, length: { maximum: 10 }


  #フォローしているかを確認するメソッド
  def following?(user)
    following_relationships.find_by(following_id: user.id)
  end

  #フォローするときのメソッド
  def follow(user)
    following_relationships.create!(following_id: user.id)
  end

  #フォローを外すときのメソッド
  def unfollow(user)
    following_relationships.find_by(following_id: user.id).destroy
  end

  def already_liked?(recipe)
   self.likes.exists?(recipe_id: recipe.id)
 end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  before_action :reject_user, only: [:create]

  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if (@user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false))
        redirect_to new_user_session_path
      else
        flash.now[:error] = "必須項目を入力してください"
      end
    else
      flash.now[:error] = "必須項目を入力してください"
    end
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user  = User.find(params[:id])
    @recipes = Recipe.where(user_id: @user.id)
    @reports = Report.where(user_id: @user.id)
  end

  def edit
    @user  = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def confirm
  end

  def hide
    #is_member_statusカラムにフラグを立てる(defaultはfalse)
    current_user.update(is_member_status: true)
    #ログアウトさせる
    reset_session
    redirect_to root_path
  end

  def following
    #@userがフォローしているユーザー
    @user  = User.find(params[:id])
    @users = @user.following
    @page_users = @users.page(params[:page]).per(10).order(created_at: :desc)
  end

  def followers
    #@userをフォローしているユーザー
    @user  = User.find(params[:id])
    @users = @user.followers
    @page_users = @users.page(params[:page]).per(10).order(created_at: :desc)
  end

  def recipes
    @user = User.find(params[:id])
    @recipes = Recipe.where(user_id: @user.id)
    @page_recipes = @recipes.page(params[:page]).per(5).order(created_at: :desc)
  end

  def likes
    @user = User.find(params[:id])
    @recipes = @user.like_recipes.includes(:user)
    @page_recipes = @recipes.page(params[:page]).per(5).order(created_at: :desc)
  end

  def reports
    @user = User.find(params[:id])
    @reports = Report.where(user_id: @user.id)
    @page_reports = @reports.page(params[:page]).per(5).order(created_at: :desc)
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:nickname,:profile_image, :profile_text, :is_meat_status, :is_fish_status, :is_egg_status, :is_dairy_products_status)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    if user_signed_in?
      if @user.id != current_user.id
       redirect_to root_path
      end
    else
      redirect_to new_user_session_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<!-- フォローボタン ------------------------------------------------------------------>
<%= form_for(current_user, url: ralationships_path, method: :post, remote: true) do |f| %>
  <%= hidden_field_tag :following_id, @user.id %>
  <%= f.submit "フォローする", class: "btn btn-outline-secondary" %>
<% end %>

app/views/users/_follow_form.html.erb
<!-- フォローボタン(MYPAGEのユーザーがcurrent_userでなければ表示------------------------------------------------------>
<% if user_signed_in? && @user != current_user %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render "unfollow" %>
    <% else %>
      <%= render "follow" %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<!-- フォロー解除ボタン ------------------------------------------------------------------>
<%= form_for(current_user, url: ralationship_path(@user), method: :delete, remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn btn-outline-secondary" %>
<% end %>

app/views/users/_user_profile.html.erb
<div class="row">
  <table class="table">
    <thead>
      <tr><th>ユーザー情報</th></tr>
    </thead>
    <tbody>
      <tr>
        <td colspan="2" align="center"><%= attachment_image_tag user, :profile_image, :fill,200,200, format: 'jpeg', class: "profile-thumb profile_image_size", fallback: "no_image.jpg" %>
          <%= render "follow_form" %>
        </td>
      </tr>
      <tr>
        <th>ニックネーム</th>
      </tr>
      <tr>
        <td class="name" align="center">
          <%= link_to user_path(user) do %>
          <strong><%= user.nickname %></strong>
          <% end %>
        </td>
      </tr>
      <tr>
        <th>自己紹介</th>
      </tr>
      <tr>
        <td colspan="2" align="center"><%= user.profile_text %></td>
      </tr>
      <tr>
        <% if current_page?(controller: 'users', action: 'reports') %>
        <tr>
          <td class="home_btn" align="center"><%= link_to "ユーザーのレシピ一覧", recipes_user_path(user),class: "btn btn-primary" %></td>
        </tr>
        <tr>
          <td class="home_btn" align="center"><%= link_to "いいねしたレシピ一覧", likes_user_path(user),class: "btn btn-primary" %></td>
        </tr>
        <% elsif current_page?(controller: 'users', action: 'recipes') %>
        <tr>
          <td class="home_btn" align="center"><%= link_to "いいねしたレシピ一覧", likes_user_path(user),class: "btn btn-primary" %></td>
        </tr>
        <tr>
          <td class="home_btn" align="center"><%= link_to "ユーザーのレポート一覧", reports_user_path(user),class: "btn btn-primary" %></td>
        </tr>
        <% elsif current_page?(controller: 'users', action: 'likes') %>
        <tr>
          <td class="home_btn" align="center"><%= link_to "ユーザーのレシピ一覧", recipes_user_path(user),class: "btn btn-primary" %></td>
        </tr>
        <tr>
          <td class="home_btn" align="center"><%= link_to "ユーザーのレポート一覧", reports_user_path(user),class: "btn btn-primary" %></td>
        </tr>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>

app/views/users/confirm.html.erb
<div class="row" align="center">
  <h1>本当に退会しますか？</h1>
</div>
<div class="row" align="center">
  <h3>
    <p>退会しても会員情報や、これまでに投稿したレシピなどは残ります。<br>
      このアカウントで、再度ログインすることはできません。<br>
      退会する場合は、「退会する」をクリックしてください。</p>
  </h3>
</div>
<div class="row" align="center">
  <tr>
    <td>
      <%= link_to "退会しない", edit_user_path(current_user), class: "btn btn-primary btn-lg" %>
    </td>
    <td>
      <%= link_to "退会する", users_hide_path(current_user), method: :put, data: {confirm: "本当に退会しますか?"}, class: "btn btn-danger btn-lg" %>
    </td>
  </tr>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <!-- エラーメッセージ -->
    <!-- エラーメッセージ -->
    <%= form_for @user, url: user_path do |f| %>
    <div class="user_profile">
      <div class="row user_profile_margin">
        <h2>ユーザー情報変更</h2>

        <% if @user.errors.any? %>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
        <% end %>
        
        <div class="col-xs-5">
          <h3>プロフィール画像</h3>
          <div align="center">
            <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", class: 'profile_image_size edit_profile_image_size', id: "profile_file-preview" %>

            <%= f.attachment_field :profile_image, class: "btn btn-primary item_attachment_field image_btn", id: "profile_image_select"%>

          </div>
        </div>
        <div class="col-xs-7">
          <h3>ニックネーム</h3>
          <%= f.text_field :nickname, class: 'form-control' %>
          <h3>自己紹介文</h3>
          <%= f.text_area :profile_text, rows:'4' ,class: 'form-control' %>
          
          <table class="table table-borderless">
            <div class="field">
              <div class="recipe_status">
                <tr>
                  <th>肉</th>
                  <td><%= f.radio_button :is_meat_status, "false" %> 表示　　<%= f.radio_button :is_meat_status, "true" %> 非表示</td>
                </tr>
              </div>
              <div class="recipe_status">
                <tr>
                  <th>魚</th>
                  <td><%= f.radio_button :is_fish_status, "false" %> 表示　　<%= f.radio_button :is_fish_status, "true" %> 非表示</td>
                </tr>
              </div>
              <div class="recipe_status">
                <tr>
                  <th>卵</th>
                  <td><%= f.radio_button :is_egg_status, "false" %> 表示　　<%= f.radio_button :is_egg_status, "true" %> 非表示</td>
                </tr>
              </div>
              <div class="recipe_status">
                <tr>
                  <th>乳製品</th>
                  <td><%= f.radio_button :is_dairy_products_status, "false" %> 表示　　<%= f.radio_button :is_dairy_products_status, "true" %> 非表示</td>
                </tr>
              </div>
            </div>
          </table>

        </div>
      </div>
    </div>
    <div class="action" align="center">
      <%= f.submit "　　ユーザー情報を変更する　　" ,class: "btn btn-primary btn-lg" %>
    </div>
    <div class="action" align="right">
      <%= link_to "退会する",  users_confirm_path, class: "btn btn-danger" %>
    </div>
    <% end %>
  </div>
</div>

<!-- 画像選択した際に、選択した画像を表示させるjavascript -->
<script>
  document.getElementById('profile_image_select').addEventListener('change', function (e) {
    // 1枚だけ表示する
    var file = e.target.files[0];

    // ファイルのブラウザ上でのURLを取得する
    var blobUrl = window.URL.createObjectURL(file);

    // img要素に表示
    var img = document.getElementById('profile_file-preview');
    img.src = blobUrl;
  });
</script>

app/views/users/followers.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1 relationships_index">
    <h2>
      <% if current_user != @user %>
      <%= @user.nickname %>のフォロワー
      <% else %>
      あなたのフォロワー
      <% end %>
    </h2>
    <table class='table'>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="5"></th>
        </tr>
      </thead>
      <tbody>
        <% @page_users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill,50,50, format: 'jpeg', class: "profile-thumb follow_image_size", fallback: "no_image.jpg" %></td>
          <td><%= user.nickname %></td>
          <td>フォロー数：<%= user.following.count %></td>
          <td>フォロワー数：<%= user.followers.count %></td>
          <td>投稿したレシピ数：<%= user.recipes.count %></td>
          <td><%= link_to '詳細へ', user_path(user),class: "btn btn-primary btn-sm" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @page_users %><br>
    <%= link_to '戻る', 'javascript:history.back()',class: "btn btn-primary btn-sm" %>
  </div>
</div>

app/views/users/following.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1 relationships_index">
    <h2>
      <% if current_user != @user %>
      <%= @user.nickname %>のフォローしているユーザー
      <% else %>
      あなたのフォローしているユーザー
      <% end %>
    </h2>
    <table class='table'>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="5"></th>
        </tr>
      </thead>
      <tbody>
        <% @page_users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill,50,50, format: 'jpeg', class: "profile-thumb follow_image_size", fallback: "no_image.jpg" %></td>
          <td><%= user.nickname %></td>
          <td>フォロー数：<%= user.following.count %></td>
          <td>フォロワー数：<%= user.followers.count %></td>
          <td>投稿したレシピ数：<%= user.recipes.count %></td>
          <td><%= link_to '詳細へ', user_path(user),class: "btn btn-primary btn-sm" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @page_users %><br>
    <%= link_to '戻る', 'javascript:history.back()',class: "btn btn-primary btn-sm back_btn" %>
  </div>
</div>

app/views/users/hide.html.erb
<h1>Users#hide</h1>
<p>Find me in app/views/users/hide.html.erb</p>

app/views/users/likes.html.erb
<div class="row">
  <div class="col-xs-3 user_profile">
    <%= render 'user_profile', user: @user %>
  </div>

  <div class="col-xs-8 recipes_index">
    <table class="table">
      <h2><%= @user.nickname %>のいいねしたレシピ</h2>
      <p>全<strong><%= @recipes.count %></strong>件</p>
      <div class="recipe_index">
        <% if @recipes.present? %>
        <% @page_recipes.each do |recipe| %>
        <div class="recipe_div">
          <tr>
            <td class="col-xs-2">
              <%= link_to recipe_path(recipe) do %>
              <%= attachment_image_tag recipe, :main_image, :fill, 120, 120, format: 'jpg', fallback: "no_image.jpg" %>
              <% end %>
              
            </td>
            <td class="col-xs-7">
              <div class="recipe_title"><%= link_to recipe.title, recipe_path(recipe) %></div>
              <%= recipe.description %>
            </td>

            <td class="col-xs-2">
              <%= link_to recipe.user.nickname, user_path(recipe.user) %>
            </td>
            <td class="col-xs-1">
              <div class="like_btn" id="show_like_<%= recipe.id %>">
                <%= render 'likes/like', recipe: recipe %>
              </div>
            </td>
            
          </tr>
        </div>
        <% end %>
        <% else %>
        <div class="recipe_no_message" align="center">いいねしたレシピはありません</div>
        <% end %>
      </div>
    </table>
    <%= paginate @page_recipes %>
  </div>
</div>

app/views/users/recipes.html.erb
<div class="row">
  <div class="col-xs-3 user_profile">
    <%= render 'user_profile', user: @user %>
  </div>

  <div class="col-xs-8 recipes_index">
    <table class="table">
      <h2><%= @user.nickname %>の投稿レシピ</h2>
      <p>全<strong><%= @recipes.count %></strong>件</p>

      <% if @recipes.present? %>
      <% @page_recipes.each do |recipe| %>
      <div class="recipe_div">
        <tr>
          <td class="col-xs-2">
            <%= link_to recipe_path(recipe) do %>
            <%= attachment_image_tag recipe, :main_image, :fill, 120, 120, format: 'jpg', fallback: "no_image.jpg" %>
            <% end %>
            
          </td>
          <td class="col-xs-7">
            <div class="recipe_title"><%= link_to recipe.title, recipe_path(recipe) %></div>
            <%= recipe.description %>
          </td>
          <td class="col-xs-2">
            <%= link_to recipe.user.nickname, user_path(recipe.user) %>
          </td>
          <td class="col-xs-1">
            <div class="like_btn" id="show_like_<%= recipe.id %>">
              <%= render 'likes/like', recipe: recipe %>
            </div>
          </td>
        </tr>
      </div>
      <% end %>
      <% else %>
      <div class="recipe_no_message" align="center">投稿レシピはありません</div>
      <% end %>
    </table>
    <%= paginate @page_recipes %>
  </div>
</div>

app/views/users/reports.html.erb
<div class="row">
  <div class="col-xs-3 user_profile">
    <%= render 'user_profile', user: @user %>
  </div>

  <div class="col-xs-8 reports_index">
    <table class="table">
      <h2><%= @user.nickname %>の投稿レポート</h2>
      <p>全<strong><%= @reports.count %></strong>件</p>

      <% if @reports.present? %>
      <% @page_reports.each do |report| %>
      <div class="report_div">
        <tr>
          <td class="col-xs-2">
            <%= link_to recipe_path(report.recipe) do %>
            <%= attachment_image_tag report, :image, :fill, 120, 120, format: 'jpg', fallback: "no_image.jpg" %>
            <% end %>
            
          </td>
          <td class="col-xs-7">
            <div class="report_title"><%= link_to report.recipe.title, recipe_path(report.recipe) %></div>
            <%= report.content %>
          </td>
          <td class="col-xs-2">
            <%= link_to report.recipe.user.nickname, user_path(report.recipe.user) %>
          </td>
        </tr>
      </div>
      <% end %>
      <% else %>
      <div class="report_no_message" align="center">投稿レポートはありません</div>
      <% end %>
    </table>
    <%= paginate @page_reports %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="col-xs-8">
      <div class="row">
        <div class="user_profile">
          <table class="table">
            <thead>
              <tr>
                <th colspan="3">ユーザー情報</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td colspan="3" align="center">
                  <%= attachment_image_tag @user, :profile_image, :fill, 200, 200, format: 'jpeg', fallback: "no_image.jpg", class: "profile_image_size" %>
                  <!-- フォローボタン -->
                  <%= render "follow_form" %>
                </td>
              </tr>
              <tr>
                <th colspan="3">ニックネーム</th>
              </tr>
              <tr>
                <td colspan="3" align="center"><strong><%= @user.nickname %></strong></td>
              </tr>
              <tr>
                <th colspan="3">自己紹介</th>
              </tr>
              <tr>
                <td colspan="3" align="center"><%= @user.profile_text %></td>
              </tr>
              <tr>
                <th class="col-xs-5">フォロー</th>
                <td class="col-xs-2" align="center" id="following_count"><%= @user.following.count %></td>
                <td class="col-xs-5"><%= link_to "フォローの一覧",  following_user_path(@user),class: "btn btn-primary" %></td>
              </tr>
              <tr>
                <th class="col-xs-5">フォロワー</th>
                <td class="col-xs-2" align="center" id="followers_count"><%= @user.followers.count %></td>
                <td class="col-xs-5"><%= link_to "フォロワーの一覧",  followers_user_path(@user),class: "btn btn-primary" %></td>
              </tr>
              <tr>
                <th class="col-xs-5">投稿したレシピ数</th>
                <td class="col-xs-2" align="center"><%= @recipes.count %></td>
                <td class="col-xs-5"><%= link_to "投稿レシピ一覧へ", recipes_user_path(@user),class: "btn btn-primary" %></td>
              </tr>
              <tr>
                <th class="col-xs-5">いいねしたレシピ数</th>
                <td class="col-xs-2" align="center"><%= @user.likes.count %></td>
                <td><%= link_to "いいねしたレシピ一覧へ", likes_user_path(@user),class: "btn btn-primary" %></td>
              </tr>
              <tr>
                <th class="col-xs-5">投稿したレポート数</th>
                <td class="col-xs-2" align="center"><%= @reports.count %></td>
                <td class="col-xs-5"><%= link_to "投稿レポート覧へ", reports_user_path(@user),class: "btn btn-primary" %></td>
              </tr>
            </tbody>
          </table>
          <div class="user_edit_btn" align="center">
            <% if current_user == @user %>
            <%= link_to "編集する", edit_user_path(@user),class: "btn btn-success btn-lg" %>
            <% end %>
          </div>
        </div>

        <div>
          <%= link_to '戻る', 'javascript:history.back()',class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <div class="col-xs-4 recipes_index">
      <h2 align="center">
        <% if current_user != @user %>
        <%= @user.nickname %>の投稿レシピ
        <% else %>
        あなたの投稿レシピ
        <% end %>
      </h2>
      <table class="table">
        <% @recipes.last(4).each do |recipe| %>
        <tbody>
          <tr>
            <td align="center">
              <%= link_to (recipe) do %>
              <%= attachment_image_tag recipe, :main_image, :fill, 180, 180,format: "jpeg" , fallback: "no_image.jpg" %><br>
              <% end %>
              <%= link_to recipe.title, recipe_path(recipe), class: "recipe_link" %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
      <% if @recipes.present? %>
      <p align="right"><%= link_to ">>ユーザのレシピをもっと見る", recipes_user_path(@user) %></p>
      <% else %>
      <p align="right">ユーザーの投稿レシピはありません</p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>