config/routes.rb
Rails.application.routes.draw do

  devise_for :users,controllers:{
    sessions: 'users/sessions'
  }

  root to: 'homes#index'

  resources :makes, only: [:create, :destroy]

  resources :ingredients, only: [:create, :destroy]

  resources :recipes do

    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    resources :reports, only: [:create, :destroy]
  end

  resources :homes, only: [:index]

  resources :likes, only: [:create, :destroy]

  get 'users/confirm' => 'users#confirm'
  patch 'users/hide' => 'users#hide'
  put 'users/hide' => 'users#hide'

  get 'users/following'
  get 'users/followers'
  get 'users/recipes'
  get 'users/likes'
  get 'users/reports'

  resources :users, only: [:show, :edit, :update] do
    member do
      get :following, :followers, :recipes, :likes, :reports
    end
  end
  resources :ralationships, only: [:create, :destroy]

  get 'homes/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord

  belongs_to :user
  belongs_to :recipe
  #バリデーション
  validates :content, presence: true, length: { maximum: 60 }
  validates :image, presence: true

  attachment :image


end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def create
    @recipe = Recipe.find(params[:recipe_id])
    #投稿に紐づいたコメントを作成
    @reports = @recipe.reports.order(:created_at)
    @report = @recipe.reports.build(report_params)
    @new_report = Report.new
    @report.user_id = current_user.id
    @report.save
    render :index
  end

  def destroy
    @new_report = Report.new
    @recipe = Recipe.find(params[:recipe_id])
    @report = Report.find(params[:id])
    @reports = @recipe.reports.order(:created_at)
    @report.destroy
    render :index
  end

  private
  def report_params
    params.require(:report).permit(:content, :image, :recipe_id, :user_id)
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<!-- コメント入力フォーム ------------------------------------------------------------>
<%= form_with(model: [recipe, report], url: recipe_reports_path(recipe) ) do |f| %>
    <%= f.attachment_field :image, class: "image_form achment_field btn btn-primary btn-xs", id: "image_select" %>
    <%= attachment_image_tag report, :image,:fill, 100,100,fallback: "no_image.jpg", class: "report_image report_image_size", id: "report_file-preview" %>
    <%= f.text_area :content, class: "report_input-mysize" %>
    <%= f.submit "送信", class: "btn btn-outline-dark report-submit float-right" %>
<% end %>

<script>
  document.getElementById('image_select').addEventListener('change', function (e) {
    // 1枚だけ表示する
    var file = e.target.files[0];

    // ファイルのブラウザ上でのURLを取得する
    var blobUrl = window.URL.createObjectURL(file);

    // img要素に表示
    var img = document.getElementById('report_file-preview');
    img.src = blobUrl;
});
</script>

app/views/reports/_index.html.erb
<% if @report.errors.any? %>
<ul>
  <% @report.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>
<!-- コメント内容(２件) ------------------------------------------------------------------>
<%= reports.count %>件コメント
<h6 class="more" data-toggle="collapse" data-target="#report_collapseExample" aria-expanded="false" aria-controls="report_collapseExample2">もっと見る....</h6>
<ul>
  <% reports.first(2).each do |report| %>
  <% unless report.id.nil? %>
  <li class="report-container">
    <div class="report-box">
      <div class="row">
        <div class="report-avatar col-xs-1">
          <%= attachment_image_tag report.user, :profile_image, :fill, 40,40, fallback: "no_image.jpg", class:"report-image small_image_size" %>
        </div>
        <p><%= link_to "@#{report.user.nickname}", user_path(report.user.id) %></p>
      </div>
      <div class="report-text">
        <div class="row">
          <div class="report_image col-xs-2">
            <%= attachment_image_tag report, :image, :fill, 100,100, fallback: "no_image.jpg", class:"report-image report_image_size" %>
          </div>
          <%= report.content %>
        </div>
        <div class="report-entry">
          <div class="row">
            <% if report.user == current_user %>
            <%= link_to recipe_report_path(report.recipe_id, report.id), method: :delete, remote: true, class: "report_destroy" do %>
            <i class="fas fa-trash pull-right" style="color: red;"></i>
            <% end %>
            <% end %>
          </div>
        </div>
        <span class="report-date pull-right">
          <%= report.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
        </span>
      </div>
    </div>
  </li>
  <% end %>
  <% end %>
</ul>
<!-- コメント内容(3件目以降) ------------------------------------------------------------------>
<div class="collapse" id="report_collapseExample">
  <ul>
    <% reports.offset(2).each do |report| %>
    <% unless report.id.nil? %>
    <li class="report-container">
      <div class="report-box">
        <div class="row">
          <div class="report-avatar col-xs-1">
            <%= attachment_image_tag report.user, :profile_image, :fill, 40,40, fallback: "no_image.jpg", class:"report-image small_image_size" %>
          </div>
          <p><%= link_to "@#{report.user.nickname}", user_path(report.user.id) %></p>
        </div>
        <div class="report-text">
          <div class="row">
            <div class="report_image col-xs-2">
              <%= attachment_image_tag report, :image, :fill, 100,100, fallback: "no_image.jpg", class:"report-image report_image_size" %>
            </div>
            <%= report.content %>
          </div>
          <div class="report-entry">
            <div class="row">
              <% if report.user == current_user %>
              <%= link_to recipe_report_path(report.recipe_id, report.id), method: :delete, remote: true, class: "report_destroy" do %>
              <i class="fas fa-trash pull-right" style="color: red;"></i>
              <% end %>
              <% end %>
            </div>
          </div>
          <span class="report-date pull-right">
            <%= report.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
          </span>
        </div>
      </div>
    </li>
    <% end %>
    <% end %>
  </ul>
</div>

app/views/reports/create.html.erb
<h1>Reports#create</h1>
<p>Find me in app/views/reports/create.html.erb</p>

app/views/reports/destroy.html.erb
<h1>Reports#destroy</h1>
<p>Find me in app/views/reports/destroy.html.erb</p>

app/views/reports/index.js.erb
$("#reports_area").html("<%= j(render 'index', { reports: @report.recipe.reports }) %>")


$("#report_form").html("<%= j(render 'reports/form', { report: @new_report, recipe: @recipe }) %>")