config/routes.rb
Rails.application.routes.draw do

  devise_for :users,controllers:{
    sessions: 'users/sessions'
  }

  root to: 'homes#index'

  resources :makes, only: [:create, :destroy]

  resources :ingredients, only: [:create, :destroy]

  resources :recipes do

    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    resources :reports, only: [:create, :destroy]
  end

  resources :homes, only: [:index]

  resources :likes, only: [:create, :destroy]

  get 'users/confirm' => 'users#confirm'
  patch 'users/hide' => 'users#hide'
  put 'users/hide' => 'users#hide'

  get 'users/following'
  get 'users/followers'
  get 'users/recipes'
  get 'users/likes'
  get 'users/reports'

  resources :users, only: [:show, :edit, :update] do
    member do
      get :following, :followers, :recipes, :likes, :reports
    end
  end
  resources :ralationships, only: [:create, :destroy]

  get 'homes/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :recipe
  #バリデーション
  validates :content, presence: true, length: { maximum: 300 }

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

  belongs_to :recipe

  validates :name, presence: true
  validates :quantity, presence: true

end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :recipe

  validates_uniqueness_of :recipe_id, scope: :user_id

end

app/models/make.rb
class Make < ApplicationRecord

  belongs_to :recipe

  attachment :image

  validates :process, presence: true, length: { maximum: 60 }

end

app/models/recipe.rb
class Recipe < ApplicationRecord

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :reports, dependent: :destroy

  attachment :main_image

  has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :ingredients, allow_destroy: true

  has_many :makes, dependent: :destroy
  accepts_nested_attributes_for :makes, allow_destroy: true

  validates :main_image, presence: true
  validates :title, presence: true, length: { maximum: 20 }
  validates :description, presence: true, length: { maximum: 80 }
  validates :point, presence: true, length: { maximum: 100 }

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  #自分をフォローしているユーザー
  belongs_to :follower, class_name: "User"
  #自分がフォローしているユーザー
  belongs_to :following, class_name: "User"
  #バリデーション
  validates :follower_id, presence: true
  validates :following_id, presence: true

end

app/models/report.rb
class Report < ApplicationRecord

  belongs_to :user
  belongs_to :recipe
  #バリデーション
  validates :content, presence: true, length: { maximum: 60 }
  validates :image, presence: true

  attachment :image


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && (self.is_member_status == false)
  end

  attachment :profile_image

  has_many :likes, dependent: :destroy
  has_many :like_recipes, through: :likes, source: :recipe

  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reports, dependent: :destroy

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship",  dependent: :destroy
  has_many :following, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  validates :profile_text, length: { maximum: 80 }
  validates :nickname, presence: true, length: { maximum: 10 }


  #フォローしているかを確認するメソッド
  def following?(user)
    following_relationships.find_by(following_id: user.id)
  end

  #フォローするときのメソッド
  def follow(user)
    following_relationships.create!(following_id: user.id)
  end

  #フォローを外すときのメソッド
  def unfollow(user)
    following_relationships.find_by(following_id: user.id).destroy
  end

  def already_liked?(recipe)
   self.likes.exists?(recipe_id: recipe.id)
 end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @all_ranks = Recipe.joins(:likes).group(:recipe_id).order(created_at: :desc)
    if user_signed_in?
      if current_user.is_meat_status
        @recipes = @recipes.where.not(is_meat_status: true)
        @all_ranks = @all_ranks.where.not(is_meat_status: true)
      end
      if current_user.is_fish_status
        @recipes = @recipes.where.not(is_fish_status: true)
        @all_ranks = @all_ranks.where.not(is_fish_status: true)
      end
      if current_user.is_egg_status
        @recipes = @recipes.where.not(is_egg_status: true)
        @all_ranks = @all_ranks.where.not(is_egg_status: true)
      end
      if current_user.is_dairy_products_status
        @recipes = @recipes.where.not(is_dairy_products_status: true)
        @all_ranks = @all_ranks.where.not(is_dairy_products_status: true)
      end
    end
    @page_recipes = @recipes.page(params[:page]).per(5)
    
    food_like_count = @all_ranks.count
    food_liked_ids = Hash[food_like_count.sort_by{ |_, v| -v }].keys
    @ranking_recipes = []
    recipes = Recipe.where(id: food_liked_ids)
    food_liked_ids[0..2].each do |id|
      @ranking_recipes << recipes.detect { |r| r.id == id }
    end
  end

  def about
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :recipe_params

  def create
    like = current_user.likes.new(recipe_id: @recipe.id)
    like.save
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, recipe_id: @recipe.id).destroy
  end

  private
  def recipe_params
    @recipe = Recipe.find(params[:recipe_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GreenCooking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="wrapper">
      <header class="navbar navbar-fixed-top">
        <% if signed_in? %>

        <div class="container">
          <nav>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to 'マイページ', user_path(current_user) %></li>
              <li><%= link_to 'レシピ一覧', recipes_path %></li>
              <li><%= link_to 'レシピ投稿', new_recipe_path %></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete%></li>
            </ul>
          </nav>
        </div>

        <% else %>

        <div class="container">
          <nav>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to 'About', homes_about_path %></li>
              <li><%= link_to 'レシピ一覧', recipes_path %></li>
              <li><%= link_to '会員登録',new_user_registration_path %></li>
              <li><%= link_to 'ログイン', new_user_session_path %></li>
            </ul>
          </nav>
        </div>

        <% end %>
      </header>

      <div class="container contents">
        <div class="row">
          <div class="col-xs-3">
            <a href="/"><%= image_tag 'logo.jpg', class:'logo', size:'200x120' %></a>
          </div>
          <div class="col-xs-4 search_form">
            <%= search_form_for @q, url: recipes_path,html: { method: :get } do |f| %>
            <%= f.text_field :title_or_description_or_ingredients_name_cont, placeholder: 'キーワードで検索', class: "form-control" %>
          </div>
          <div class="col-xs-1 search_form search_btn">
            <%= f.submit "検索",class: "btn btn-primary" %>
          </div>
          <% end %>
        </div>
        <%= yield %>
      </div>

      <footer>
        <div class="container">
          <h5 class="col-xs-7"><%= link_to 'About「Green Cooking」',homes_about_path %></h5>
          <span id="back">
            <a href="#">
              <h5 class="col-xs-2">ページトップへ</h5>
            </a>
          </span>
        </div>
      </footer>
    </div>
  </body>
</html>